# Generated by Django 3.2.9 on 2021-12-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myforum',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
