# Generated by Django 3.2.9 on 2021-11-27 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='myForum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.myforum'),
        ),
        migrations.AlterField(
            model_name='myforum',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
