# Generated by Django 3.2.9 on 2021-11-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20211126_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='name',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
