# Generated by Django 3.2.9 on 2021-12-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_myforum_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myforum',
            name='description',
            field=models.TextField(),
        ),
    ]
