# Generated by Django 3.2.9 on 2021-11-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_discussion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=200),
        ),
    ]
