# Generated by Django 3.2.9 on 2021-12-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_discussion_myforum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='myForum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.myforum'),
        ),
    ]
