# Generated by Django 3.2.9 on 2021-12-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_discussion_myforum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='date_created',
        ),
    ]
