# Generated by Django 3.2.9 on 2021-11-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_discussion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myforum',
            name='name',
            field=models.CharField(blank=True, default='anonymous', max_length=200),
        ),
    ]
