# Generated by Django 3.2.9 on 2021-12-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_discussion_csrf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='csrf',
        ),
    ]
