# Generated by Django 3.2.9 on 2021-12-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_myforum_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myforum',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myforum',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
