# Generated by Django 3.2.9 on 2021-12-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_discussion_discuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.CharField(max_length=1000),
        ),
    ]
