# Generated by Django 3.2.9 on 2021-12-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_discussion_discuss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myforum',
            name='date_created',
        ),
    ]
