# Generated by Django 3.2.9 on 2021-11-21 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=75)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('furnished', models.CharField(default='No', max_length=3)),
                ('parking', models.CharField(default='No', max_length=20)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=200)),
                ('services', models.TextField(default='')),
                ('amenities', models.TextField(default='')),
                ('favorite', models.BooleanField(default=False)),
                ('floorplan_file_name', models.CharField(default='/static/floorplans/floorplan.jpg', max_length=100)),
                ('picture_file_name', models.CharField(default='/static/pictures/sample_house.jpg', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities_rating', models.DecimalField(decimal_places=0, default=5, max_digits=1)),
                ('services_rating', models.DecimalField(decimal_places=0, default=5, max_digits=1)),
                ('noise_level_rating', models.DecimalField(decimal_places=0, default=5, max_digits=1)),
                ('property', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='housing_app.property')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
