# Generated by Django 3.2.9 on 2021-11-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
