# Generated by Django 3.2.8 on 2021-10-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
