# Generated by Django 3.2.8 on 2021-10-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0004_auto_20211012_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=7)),
                ('utilities', models.DecimalField(decimal_places=2, max_digits=7)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
