# Generated by Django 3.2.8 on 2021-10-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0005_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=7),
            preserve_default=False,
        ),
    ]
