# Generated by Django 3.2.8 on 2021-10-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0006_property_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='113 Harmon St, Charlottesville VA 22903', max_length=200),
            preserve_default=False,
        ),
    ]
