# Generated by Django 3.2.8 on 2021-10-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0007_property_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
    ]
