# Generated by Django 3.2.7 on 2021-10-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0008_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amentities',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='services',
            field=models.TextField(default=''),
        ),
    ]
