# Generated by Django 3.2.7 on 2021-10-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0009_auto_20211027_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='utilities',
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.TextField(default=''),
        ),
    ]
