# Generated by Django 3.2.8 on 2021-10-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0011_auto_20211031_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.CharField(default='', max_length=3),
        ),
    ]
