# Generated by Django 3.2.8 on 2021-10-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0012_property_furnished'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(default='', max_length=3),
        ),
    ]
