# Generated by Django 3.2.8 on 2021-11-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0013_property_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities_rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='property',
            name='management',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='property',
            name='noise_level',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.CharField(default='', max_length=20),
        ),
    ]
