# Generated by Django 3.2.9 on 2021-11-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0014_alter_property_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default=1),
        ),
    ]
