# Generated by Django 3.2.8 on 2021-11-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0015_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amenities_rating',
        ),
        migrations.RemoveField(
            model_name='property',
            name='management',
        ),
        migrations.RemoveField(
            model_name='property',
            name='noise_level',
        ),
        migrations.RemoveField(
            model_name='review',
            name='deepthought',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='amenities_rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='review',
            name='management',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='review',
            name='noise_level',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
