# Generated by Django 3.2.8 on 2021-11-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0016_auto_20211113_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='avg_amenities',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=1),
        ),
        migrations.AddField(
            model_name='review',
            name='property_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='amenities_rating',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='management',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='noise_level',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=1),
        ),
    ]
