# Generated by Django 3.2.9 on 2021-11-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0016_auto_20211106_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False),
        ),
    ]
