# Generated by Django 3.2.9 on 2021-11-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0017_auto_20211106_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='furnished',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.CharField(default='No', max_length=20),
        ),
    ]
