# Generated by Django 3.2.9 on 2021-11-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0014_auto_20211107_2317'),
        ('housing_app', '0018_auto_20211106_1809'),
    ]

    operations = [
    ]
