# Generated by Django 3.2.8 on 2021-11-14 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0018_rename_property_title_review_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rooms',
        ),
    ]
