# Generated by Django 3.2.8 on 2021-11-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0019_remove_property_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.TextField(default=''),
        ),
    ]
