# Generated by Django 3.2.7 on 2021-11-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0020_alter_property_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='picture',
            field=models.ImageField(default='', upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(max_length=75),
        ),
    ]
