# Generated by Django 3.2.9 on 2021-11-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0021_auto_20211111_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
