# Generated by Django 3.2.9 on 2021-11-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0018_rename_property_title_review_review_title'),
        ('housing_app', '0022_property_favorite'),
    ]

    operations = [
    ]
