# Generated by Django 3.2.9 on 2021-11-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0023_merge_20211114_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.CharField(default='No', max_length=20),
        ),
    ]
