# Generated by Django 3.2.9 on 2021-11-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0024_alter_property_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='floorplan',
        ),
        migrations.RemoveField(
            model_name='property',
            name='picture',
        ),
        migrations.AddField(
            model_name='property',
            name='floorplan_file_name',
            field=models.CharField(default='floorplan.jpg', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='picture_file_name',
            field=models.CharField(default='sample_house.jpg', max_length=20),
        ),
    ]
