# Generated by Django 3.2.9 on 2021-11-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0027_auto_20211120_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floorplan_file_name',
            field=models.CharField(default='/static/floorplans/floorplan.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_file_name',
            field=models.CharField(default='/static/pictures/sample_house.jpg', max_length=100),
        ),
    ]
