# Generated by Django 3.2.9 on 2021-11-21 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0028_auto_20211120_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities_rating', models.DecimalField(decimal_places=0, default=5, max_digits=1)),
                ('services_rating', models.DecimalField(decimal_places=0, default=5, max_digits=1)),
                ('noise_level_rating', models.DecimalField(decimal_places=0, default=5, max_digits=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RemoveField(
            model_name='property',
            name='avg_amenities',
        ),
        migrations.AddField(
            model_name='rating',
            name='property',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='housing_app.property'),
        ),
    ]
