# Generated by Django 3.2.9 on 2021-11-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0028_auto_20211120_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lat',
            field=models.FloatField(default=38.034493639911936),
        ),
        migrations.AddField(
            model_name='property',
            name='lon',
            field=models.FloatField(default=-78.50999182771713),
        ),
    ]
