# Generated by Django 3.2.9 on 2021-11-27 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0028_auto_20211120_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='favorite',
        ),
    ]
