# Generated by Django 3.2.9 on 2021-11-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0029_auto_20211121_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='management',
            new_name='noise_level_rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='noise_level',
            new_name='services_rating',
        ),
    ]
