# Generated by Django 3.2.9 on 2021-11-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0029_auto_20211123_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='avg_amenities',
        ),
    ]
