# Generated by Django 3.2.9 on 2021-11-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0030_auto_20211121_1138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Rating',
        ),
    ]
