# Generated by Django 3.2.9 on 2021-11-25 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0030_auto_20211123_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='amenities_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='noise_level_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='property',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='services_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
