# Generated by Django 3.2.9 on 2021-11-25 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0031_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='favorite',
        ),
        migrations.AddField(
            model_name='property',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='fav_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
