# Generated by Django 3.2.9 on 2021-11-25 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0031_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
