# Generated by Django 3.2.9 on 2021-11-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0031_rename_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='property',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='housing_app.property'),
        ),
    ]
