# Generated by Django 3.2.9 on 2021-11-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0031_auto_20211124_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='property',
            field=models.TextField(default='', max_length=200),
        ),
    ]
