# Generated by Django 3.2.9 on 2021-11-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0032_remove_rating_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='property_id',
            field=models.IntegerField(default=-1),
        ),
    ]
