# Generated by Django 3.2.9 on 2021-11-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0032_alter_rating_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='housing_app.property'),
        ),
    ]
