# Generated by Django 3.2.9 on 2021-11-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0033_rating_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='avg_amenities',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='property_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
