# Generated by Django 3.2.9 on 2021-11-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0029_remove_property_favorite'),
        ('housing_app', '0035_auto_20211129_1707'),
    ]

    operations = [
    ]
