# Generated by Django 3.2.9 on 2021-11-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0035_auto_20211129_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='biased_review',
            field=models.BooleanField(default=False),
        ),
    ]
