# Generated by Django 3.2.9 on 2021-12-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0032_auto_20211125_0204'),
        ('housing_app', '0036_review_biased_review'),
    ]

    operations = [
    ]
